function Ji = FJi_AWGV(Ri,Rj,ri,rj,t,xi,xj,yi,yj)
%FJI_AWGV
%    JI = FJI_AWGV(RI,RJ,RI,RJ,T,XI,XJ,YI,YJ)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Apr-2017 00:17:20

t2 = yi.*1i;
t3 = yj.*-1i;
t4 = t2+t3+xi-xj;
t5 = conj(t);
t6 = cosh(t5);
t7 = abs(t4);
t8 = Rj.*(1.0./2.0);
t9 = ri.*(1.0./2.0);
t10 = rj.*(1.0./2.0);
t18 = Ri.*(1.0./2.0);
t11 = t8+t9+t10-t18;
t12 = sign(t4);
t13 = conj(t12);
t14 = 1.0./t7.^2;
t15 = xi-xj;
t16 = abs(t15);
t19 = yi-yj;
t17 = abs(t19);
t20 = sinh(t5);
t21 = 1.0./t7;
t22 = t16.^2;
t23 = t22.*(1.0./4.0);
t24 = t17.^2;
t25 = t24.*(1.0./4.0);
t26 = t11.^2;
t27 = t23+t25-t26;
t28 = sqrt(t27);
t29 = conj(t28);
t30 = sign(t15);
t31 = 1.0./t29;
t32 = t20.*t21.*t29;
t33 = t6.*t11.*t21;
t34 = sign(t19);
Ji = reshape([t33-t6.*t11.*t13.*t14.*t15+t13.*t14.*t19.*t20.*t29-t16.*t19.*t20.*t21.*t30.*t31.*(1.0./4.0)+1.0./2.0,-t32+t6.*t11.*t13.*t14.*t15.*1i-t13.*t14.*t19.*t20.*t29.*1i-t17.*t19.*t20.*t21.*t31.*t34.*(1.0./4.0),t32-t6.*t11.*t13.*t14.*t19-t13.*t14.*t15.*t20.*t29+t15.*t16.*t20.*t21.*t30.*t31.*(1.0./4.0),t33+t6.*t11.*t13.*t14.*t19.*1i+t13.*t14.*t15.*t20.*t29.*1i+t15.*t17.*t20.*t21.*t31.*t34.*(1.0./4.0)+1.0./2.0],[2,2]);
