function Jj = FJj_AWGV(Ri,Rj,ri,rj,t,xi,xj,yi,yj)
%FJJ_AWGV
%    JJ = FJJ_AWGV(RI,RJ,RI,RJ,T,XI,XJ,YI,YJ)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Apr-2017 00:17:21

t2 = yi.*1i;
t3 = yj.*-1i;
t4 = t2+t3+xi-xj;
t5 = conj(t);
t6 = cosh(t5);
t7 = abs(t4);
t8 = Ri.*(1.0./2.0);
t9 = ri.*(1.0./2.0);
t10 = rj.*(1.0./2.0);
t18 = Rj.*(1.0./2.0);
t11 = t8+t9+t10-t18;
t12 = sign(t4);
t13 = conj(t12);
t14 = 1.0./t7.^2;
t15 = xi-xj;
t16 = abs(t15);
t20 = yi-yj;
t17 = abs(t20);
t19 = -t8+t9+t10+t18;
t21 = sinh(t5);
t22 = 1.0./t7;
t23 = t16.^2;
t24 = t23.*(1.0./4.0);
t25 = t17.^2;
t26 = t25.*(1.0./4.0);
t27 = t19.^2;
t28 = t24+t26-t27;
t29 = sqrt(t28);
t30 = conj(t29);
t31 = sign(t15);
t32 = 1.0./t30;
t33 = sign(t20);
Jj = reshape([-t6.*t11.*t22+t6.*t11.*t13.*t14.*t15-t13.*t14.*t20.*t21.*t30+t16.*t20.*t21.*t22.*t31.*t32.*(1.0./4.0)+1.0./2.0,t21.*t22.*t30-t6.*t11.*t13.*t14.*t15.*1i+t13.*t14.*t20.*t21.*t30.*1i+t17.*t20.*t21.*t22.*t32.*t33.*(1.0./4.0),-t21.*t22.*t30+t6.*t11.*t13.*t14.*t20+t13.*t14.*t15.*t21.*t30-t15.*t16.*t21.*t22.*t31.*t32.*(1.0./4.0),-t6.*t11.*t22-t6.*t11.*t13.*t14.*t20.*1i-t13.*t14.*t15.*t21.*t30.*1i-t15.*t17.*t21.*t22.*t32.*t33.*(1.0./4.0)+1.0./2.0],[2,2]);
