function Ji = FJi_AWGV(Ri,Rj,ri,rj,t,xi,xj,yi,yj)
%FJI_AWGV
%    JI = FJI_AWGV(RI,RJ,RI,RJ,T,XI,XJ,YI,YJ)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    24-Apr-2017 11:51:43

t2 = yi.*1i;
t3 = yj.*-1i;
t4 = t2+t3+xi-xj;
t5 = abs(t4);
t17 = xi-xj;
t6 = abs(t17);
t12 = yi-yj;
t7 = abs(t12);
t8 = Rj.*(1.0./2.0);
t9 = ri.*(1.0./2.0);
t10 = rj.*(1.0./2.0);
t18 = Ri.*(1.0./2.0);
t11 = t8+t9+t10-t18;
t13 = sign(t4);
t14 = conj(t13);
t15 = 1.0./t5.^2;
t16 = cosh(t);
t19 = 1.0./t5;
t20 = sinh(t);
t21 = t6.^2;
t22 = t21.*(1.0./4.0);
t23 = t7.^2;
t24 = t23.*(1.0./4.0);
t25 = t11.^2;
t26 = t22+t24-t25;
t27 = sqrt(t26);
t28 = conj(t27);
t29 = sign(t17);
t30 = 1.0./t28;
t31 = t19.*t20.*t28;
t32 = t11.*t16.*t19;
t33 = sign(t12);
Ji = reshape([t32-t11.*t14.*t15.*t16.*t17+t12.*t14.*t15.*t20.*t28-t6.*t12.*t19.*t20.*t29.*t30.*(1.0./4.0)+1.0./2.0,-t31+t11.*t14.*t15.*t16.*t17.*1i-t12.*t14.*t15.*t20.*t28.*1i-t7.*t12.*t19.*t20.*t30.*t33.*(1.0./4.0),t31-t11.*t12.*t14.*t15.*t16-t14.*t15.*t17.*t20.*t28+t6.*t17.*t19.*t20.*t29.*t30.*(1.0./4.0),t32+t11.*t12.*t14.*t15.*t16.*1i+t14.*t15.*t17.*t20.*t28.*1i+t7.*t17.*t19.*t20.*t30.*t33.*(1.0./4.0)+1.0./2.0],[2,2]);
